site_name: Yarin Akiva - Portfolio
theme: 
    name: material
    custom_dir: overrides
    font: false
    features: []  # מסיר את כל התכונות המיוחדות
    palette:
        primary: indigo
        accent: indigo
    icon:
        logo: material/code  # מסיר את האייקון המובנה
    language: en
    search: false  # מבטל את החיפוש
    navigation_depth: 0  # מבטל את תפריט הניווט הצדדי

extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css
    - assets/css/custom.css

extra_javascript:
    - assets/js/script.js

markdown_extensions:
    - meta
    - attr_list
    - md_in_html

nav: []  