site_name: Yarin Akiva - Portfolio
theme: 
    name: material
    language: en
    custom_dir: overrides
    font: false
    features: []
    palette:
        scheme: light
plugins: []
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css
    - assets/css/custom.css
extra_javascript:
    - assets/js/script.js
markdown_extensions:
    - meta
    - attr_list
    - md_in_html
nav:
    - Home: index.md
    - About: about.md
    - Certificates: certificates.md
    - Projects: projects.md