name: Deploy Static Website to AWS S3 and CloudFront
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      - name: Build site
        run: mkdocs build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload to S3
        run: |
          aws s3 sync ./site s3://${{ env.BUCKET_NAME }} \
            --delete \
            --cache-control "max-age=3600" \
            --exclude "*.html" \
            --exclude "*.css" \
            --exclude "*.js"
          aws s3 sync ./site s3://${{ env.BUCKET_NAME }} \
            --delete \
            --cache-control "no-cache" \
            --include "*.html" \
            --include "*.css" \
            --include "*.js"
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DISTRIBUTION_ID }} \
            --paths "/*"